gskdfhyjhd

diff --git a/pgit b/pgit
--- a/pgit
+++ b/pgit
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
 
 pull=$(git pull)
-echo "$pull"
 
-if [ "$pull" -ne 0 ]
+if [[ "$pull" == *"error"* ]]
 then
-	echo "Fix git pull error as seen, and run script again"
-	exit 
+	echo "Fix git pull error as seen in the following output, and run script again"
+	echo "$pull"
+	exit 1
 fi
 
 git add .
